package org.kumoricon.model.user;

import com.vaadin.annotations.AutoGenerated;
import jdk.nashorn.internal.runtime.regexp.joni.exception.ValueException;
import org.kumoricon.model.role.Role;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import java.io.Serializable;
import java.math.BigInteger;

@Entity
public class User implements Serializable {
    @Id
    @AutoGenerated
    private Integer id;
    private String username;
    private String password;
    private String phone;
    private Boolean enabled;
    @ManyToOne
    private Role role;
    private String salt;

    public User() {
        this.id = null;
        this.salt = "TempSalt"; // Todo: randomly generate salt
        this.enabled = true;
    }

    public User(String username, String password) {
        this();
        setUsername(username);
        setPassword(password);
    }

    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username.toLowerCase(); }

    public String getPassword() { return password; }
    public void setPassword(String newPassword) {
        if (newPassword == null || newPassword.trim().equals("")) {
            throw new ValueException("Password cannot be blank");
        }
        this.password = hashPassword(newPassword, salt);
    }

    public Boolean checkPassword(String password) {
        return (hashPassword(password, salt).equals(this.password));
    }

    public Role getRole() { return role; }
    public void setRole(Role role) { this.role = role; }

    public String getSalt() { return salt; }
    public void setSalt(String salt) { this.salt = salt; }

    public Boolean getEnabled() { return enabled; }
    public void setEnabled(Boolean enabled) { this.enabled = enabled; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    private static String hashPassword(String password, String salt){
        char[] passwordChars = password.toCharArray();
        byte[] saltBytes = salt.getBytes();

        PBEKeySpec spec = new PBEKeySpec(
                passwordChars,
                saltBytes,
                1000,
                256);
        byte[] hashedPassword;
        try {
            SecretKeyFactory key = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
            hashedPassword = key.generateSecret(spec).getEncoded();
            return String.format("%x", new BigInteger(hashedPassword));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return null;
    }

    public String toString() { return this.username; }
}
