package org.kumoricon.model.role;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

@Entity
public class Right {
    @Id
    @AutoGenerated
    private Integer id;
    @NotNull
    private String name;

    public String toString() {
        return String.format("%d - %s", id, name);
    }

}
