package org.kumoricon.model.role;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import java.util.HashSet;
import java.util.Set;

@Entity
public class Role {
    @Id
    @AutoGenerated
    private Integer id;
    @NotNull
    private String name;
    private Set<String> rights;

    private static String[] availableRights = {"Pre Reg Check In", "At Con Check In", "Attendee Search",
            "Attendee Modify", "Set Manual Price", "Manage Pass Types", "Edit Notes", "Manage Staff", "Override",
            "Reprint Badge"};

    public Role(String name) {
        this.name = name;
        this.rights = new HashSet<String>();
    }

    public Integer getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public void addRight(String right) { rights.add(right); }
    public void addRights(Set<String> rights) { this.rights.addAll(rights); }
    public void removeRight(String right) { rights.remove(right); }
    public Set<String> getRights() { return new HashSet<String>(rights); }
    public boolean hasRight(String name) { return rights.contains(name); }

    public String toString() {
        return name;
    }

    public String[] getAvailableRights() {
        return availableRights;
    }

    public void clearRights() {
        this.rights.clear();
    }
}
